source "$HOME/.config/zsh/local"
source "$HOME/.config/zsh/prompt"
source "$HOME/.config/zsh/vimode"
source "$HOME/.config/zsh/alias"
source "$HOME/.config/zsh/plugin"
export PATH="$HOME/.local/bin:$PATH"
