#! /bin/zsh

# share/opencode is for copilot creds
docker run -it --rm \
  --memory="2g" \
  -v "app-source-code:/project" \
  -w /project \
  -v ~/.local/share/opencode:/root/.local/share/opencode \
  -v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock \
  -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" \
  ghcr.io/anomalyco/opencode:2.0.16
