# no need for the clock in status line
set -g status-right ""

# Use Vi keys in the status bar command prompt (Ctrl+b -> :)
set -g status-keys vi

# Enable mouse support
set -g mouse on

##
## macOS copy/paste
##

# Use vi keys in copy mode
set-window-option -g mode-keys vi

# Bind 'v' to begin selection
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Bind 'y' to copy and send to macOS pbcopy
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Bind 'Enter' to copy and send to macOS pbcopy
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Bind mouse drag end to copy to macOS pbcopy
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

##
## End macOS copy/paste
## 


