# no need for the clock in status line
set -g status-right ""

# Use Vi keys in copy mode (scrolling/selecting)
setw -g mode-keys vi

# Use Vi keys in the status bar command prompt (Ctrl+b -> :)
set -g status-keys vi

